name: ArmorStandEditor
version: "1.21"
main: io.github.rypofalem.armorstandeditor.ArmorStandEditorPlugin
api-version: "1.21"
authors: [RypoFalem, mercurialmusic]
description: Allows players to edit data of armorstands without any commands.
commands:
  ase:
    description: Changes the function of the armorstand edit tool.
    usage: /<command> ? - list subcommands
    permission: asedit.basic
permissions:
  asedit.basic:
    description: Allow use armorstand edit functions. If set to false it will override all other functions.
    default: false
  asedit.invisible:
    description: Toggle armorstand visible/invisible.
    default: false
  asedit.rename:
    description: Rename armorstands
    default: false
